name: 'Dokploy Deployment Fixed'
description: 'Trigger a Dokploy deployment'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  dokploy_url:
    description: 'Dokploy base URL, e.g. https://deploy.nyxalis.xyz'
    required: true
  auth_token:
    description: 'Dokploy authentication token'
    required: true
  application_id:
    description: 'Dokploy application ID'
    required: true
runs:
  using: "composite"
  steps:
    - name: Trigger Dokploy deployment
      shell: bash
      env:
        DOKPLOY_URL: ${{ inputs.dokploy_url }}
        DOKPLOY_AUTH_TOKEN: ${{ inputs.auth_token }}
        DOKPLOY_APPLICATION_ID: ${{ inputs.application_id }}
      run: |
        response=$(curl -X 'POST' \
          "$DOKPLOY_URL/api/application.deploy" \
          -H 'Accept: */*' \
          -H 'Accept-Encoding: deflate, gzip' \
          -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0' \
          -H 'Host: deploy.nyxalis.xyz' \
          -H "x-api-key: $DOKPLOY_AUTH_TOKEN" \
          -H 'Content-Type: application/json' \
          -d "{\"applicationId\": \"$DOKPLOY_APPLICATION_ID\"}" \
          -w "%{http_code}" \
          -o /dev/null \
          -s)
        
        if [ "$response" -ne 200 ]; then
          echo "Deployment failed with status code: $response"
          exit 1
        fi
